#!/bin/sh
# clear the image displayed by ueberzug.
[ -p "$PREVIEW_FIFO" ] &&
    sed -nz '3q1;/\/ueberzug/q0' "/proc/$(cat "$PREVIEW_PID")/cmdline" 2>/dev/null &&
    echo '{"action":"remove","identifier":"lfpreview"}' > "$PREVIEW_FIFO"
