#!/bin/sh

main()
{
    cmd=img
    case "$1" in
        -i) cmd=init ;;
        -k) cmd=kill ;;
    esac
    $cmd "$@"
}

img()
{
}

init()
{
    is_in_graphical_env || return 1
    command -v ueberzug >/dev/null || return 1

}

is_in_graphical_env ()
{
    [ -n "$DISPLAY" ] && [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ] && return 0
    return 1
}


main "$@"
exit
