#!/bin/sh
# print the last directory the latest closed lf instance was in.
case "$1" in
    -remote|-doc|-version|-server|-help) exit ;;
esac
last_dir="${XDG_RUNTIME_DIR:-/tmp}/lf/lastdir"
cat "$last_dir" || echo lflast: couldn\'t get last dir. >&2
rm -f "$last_dir"
