#!/bin/sh
# mount archives from lf. requires archivemount.
# usage: $ lfmount [-p] ARCHIVE_FILE

while getopts i:up opt; do
    case $opt in
        i) export id="$OPTARG" ;;
        p) pass='-o password' ;;
        ?) exit 1 ;;
    esac
done
shift $((OPTIND-1))
[ -z "$id" ] && lf\'s id is not given. >&2 && exit 1

mnt="$1.$(mktemp -u XXXXXX).ArchiveMount"
mkdir -p "$mnt" || {
    lf -remote "send $id echo failed creating the mountpoint here."
    exit 1
}

output="$(archivemount -o readonly $pass "$1" "$mnt" 2>&1)"
if [ "$(ls -A "$mnt" | wc -l)" -le 0 ]; then
    fusermount -u "$mnt"
    rm -rf "$mnt"
    lf -remote "send $id echo mount failed: $output"
    exit 1
fi

mnt="$(printf '%s\n' "$mnt" | sed 's/"/\\"/g')"
lf -remote "send $id cd \"$mnt\""
