#!/bin/sh
# run lf with support for ueberzug image previews and lflast.

# config
tmp="${XDG_RUNTIME_DIR:-/tmp}/lf"
export FIFO="$tmp/fifo-$$"

main()
{
    case "$1" in
        -remote|-doc|-version|-server|-help)
            lf "$@"
            return
        ;;
    esac

    mkdir -p "$tmp"
    preview_init
    lf -last-dir-path="$tmp/lastdir" "$@"
}

preview_init()
{
    [ -z "$DISPLAY" ] && return 1
    command -v ueberzug >/dev/null || return 1

    trap 'rm -f "$FIFO"; pkill -P $$' EXIT
    rm -f "$FIFO"
    mkfifo "$FIFO" || return 1
    sleep inf > "$FIFO" &
    sh < "$FIFO" &
}

main "$@"
