#!/bin/sh
# run lf with support for ueberzug image previews and lflast.

# config
cache_dir="${XDG_RUNTIME_DIR:-/tmp}/lf"
last_dir_local="$(mktemp -u "$cache_dir/lastdirlocal/XXXXXX")"
last_dir_global="$cache_dir/lastdir"
fifo="$cache_dir/fifo/$$"

main ()
{
    case "$1" in
        -remote|-doc|-version|-server|-help)
            lf "$@"
            return
        ;;
    esac

    trap cleanup EXIT
    ueberzug_init
    mkdir -p "$(dirname "$last_dir_local")"
    lf -last-dir-path="$last_dir_local" "$@"
    rm -f "$last_dir_global"
    mv "$last_dir_local" "$last_dir_global" >/dev/null 2>&1
}

ueberzug_init ()
{
    is_in_graphical_env || return 1
    command -v ueberzug >/dev/null || return 1

    mkdir -p "$(dirname "$fifo")"
    find "$(dirname "$fifo")" -type f -delete
    mkfifo "$fifo"

    sleep 1000000000 > "$fifo" &
    sleep_pid=$!

    ueberzug layer -s < "$fifo" &
    export FIFO_UEBERZUG="$fifo"
}

cleanup ()
{
    [ -n "$sleep_pid" ] && kill $sleep_pid
    rm -f "$fifo" "$last_dir_local"
}

is_in_graphical_env ()
{
    [ -n "$DISPLAY" ] && [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ] && return 0
    return 1
}

main "$@"
exit
