#!/bin/sh
# run lf with support for ueberzug image previews and lflast.

# config
tmp="${XDG_RUNTIME_DIR:-/tmp}/lf"
export PREVIEW_FIFO="$tmp/fifo-$$"
export PREVIEW_STATE="$tmp/tpw-$$"

main ()
{
    case "$1" in
        -remote|-doc|-version|-server|-help)
            lf "$@"
            return
        ;;
    esac

    trap cleanup EXIT
    mkdir -p "$tmp"
    ueberzug_init
    lf -last-dir-path="$tmp/lastdir" "$@"
}

ueberzug_init ()
{
    is_in_graphical_env || return 1
    command -v ueberzug >/dev/null || return 1

    mkfifo "$PREVIEW_FIFO" || return 1

    sleep 1000000000 > "$PREVIEW_FIFO" &
    sleep_pid=$!

    ueberzug layer -s < "$PREVIEW_FIFO" &
}

cleanup ()
{
    [ -n "$sleep_pid" ] && kill $sleep_pid
    rm -f "$PREVIEW_FIFO" "$PREVIEW_STATE"
}

is_in_graphical_env ()
{
    [ -n "$DISPLAY" ] && [ -z "$SSH_CLIENT" ] && [ -z "$SSH_TTY" ] && return 0
    return 1
}

main "$@"
exit
