#!/bin/sh
# read filenames from stdin/args and select them in lf.

# check $id
[ -z "$id" ] && echo lf\'s id is not given. >&2 && exit 1

sed 's/"/\\"/g' | while IFS= read -r file; do
    [ -n "$file" ] && lf -remote "send $id select \"$file\"
send $id toggle"
done
