#!/bin/sh
# open images in sxiv with support for lf.

# pattern for matching image files
regex="${LF_IMG_REGEX:-.*\.(jpe?g|png|gif|bmp|ico)$}"

while getopts i: opt; do
    case $opt in
        i) export id="$OPTARG" ;;
        ?) exit 1 ;;
    esac
done
shift $((OPTIND-1))
[ -z "$id" ] && echo id of lf is not given. >&2 && exit 1

# check if at least one image is given
[ -z "$*" ] && echo give image >&2 && exit 1

# check if sxiv is installed
! command -v sxiv >/dev/null && echo lfsxiv requires sxiv. >&2 && exit 1

# go to directory of image(s)
cd "$(dirname "$1")" || exit 1

# build a list of all images to open, one per line
list="$(
    [ $# -gt 1 ] && printf '%s\n' "$@" && exit
    find -L -mindepth 1 -maxdepth 1 -type f \
        -regextype egrep -iregex "$regex" -printf '%f\n'
)"

# find the number of the selected image amongst the list
num="$(
    [ $# -gt 1 ] && echo 1 && exit
    printf '%s\n' "$list" | awk -v i="$(basename "$1")" '$0==i{print NR}'
)"

# open images in sxiv
sel="$(printf '%s\n' "$list" | sxiv -aion$num)"

# select sxiv's selection in lf
[ -z "$sel" ] && exit
printf '%s\n' "$sel" | lfselect
