#!/bin/sh
# toggle lf's preview and re-adjust ratios.
# usage:   $ lftp $id <no-preview-ratios> <preview-ratios>
# example: $ lftp 123 1 2:1

# config
lftmp="${XDG_RUNTIME_DIR:-/tmp}/lf"
cache="$lftmp/togglepreview"
status="$cache/$id"
fifo_dir="$lftmp/fifo"

main ()
{
    [ -z "$*" ] && exit 1
    id="$1"
    npr="$2" # no preview ratios
    pr="$3" # preview ratios
    initial="$4" # initial preview status
    toggle_preview
}

toggle_preview ()
{
    if is_preview_on; then
        set_preview_off
    else
        set_preview_on
    fi
}

is_preview_on ()
{
    [ "$initial" = off ] && initial=1 || initial=0
    return "$(cat "$status" 2>/dev/null || $initial)"
}

set_preview_on ()
{
    lf -remote "
        send $id set ratios $pr
        send $id set preview
        send $id load
    "
    echo 0 > "$status"
}

set_preview_off ()
{
    lf -remote "
        send $id set nopreview
        send $id set ratios $npr
    "
    echo 1 > "$status"
    sleep 0.1
    cleanup_preview
}

cleanup_preview ()
{
    find "$fifo_dir" -type p |
        while IFS= read -r fifo; do
            export FIFO_UEBERZUG="$fifo"
            lfcleaner
        done
}

main "$@"
exit
