#!/bin/sh
# toggle lf's preview and re-adjust ratios.
# usage:   $ lftp $id <no-preview-ratios> <preview-ratios>
# example: $ lftp 123 1 2:1

main ()
{
    while getopts i: opt; do
        case $opt in
            i) export id="$OPTARG" ;;
            ?) exit 1 ;;
        esac
    done
    shift $((OPTIND-1))
    [ -z "$id" ] && echo id of lf is not given. >&2 && exit 1

    [ -z "$*" ] && exit 1
    npr="$1"      # no preview ratios
    pr="$2"       # preview ratios
    initial="$3"  # initial preview state
    toggle_preview
}

toggle_preview ()
{
    if is_preview_on; then
        set_preview_off
    else
        set_preview_on
    fi
}

is_preview_on ()
{
    [ "$initial" = off ] && initial=1 || initial=0
    return "$(cat "$PREVIEW_STATE" 2>/dev/null || echo $initial)"
}

set_preview_on ()
{
    lf -remote "send $id push :set<space>ratios<space>$pr;set<space>preview;load<enter>"
    echo 0 > "$PREVIEW_STATE"
}

set_preview_off ()
{
    head -n1 "$PREVIEW_FIFO" >/dev/null &
    lfcleaner
    lf -remote "send $id push :set<space>nopreview;set<space>ratios<space>$npr<enter>"
    sleep 0.2 && lfcleaner
    echo 1 > "$PREVIEW_STATE"
    wait
}

main "$@"
exit
